apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-config-sync.fullname" . }}
  labels:
    {{- include "prometheus-config-sync.labels" . | nindent 4 }}
data:
  PROMETHEUS_CONFIG_SYNC_SOURCE_URL: {{ .Values.config.sourceURL | quote }}
  PROMETHEUS_CONFIG_SYNC_PROMETHEUS_RELOAD_URL: {{ .Values.config.prometheusReloadURL | quote }}
  PROMETHEUS_CONFIG_SYNC_OUTPUT_DIR: {{ .Values.config.outputDir | quote }}
  PROMETHEUS_CONFIG_SYNC_PROMTOOL_PATH: {{ .Values.config.promtoolPath | quote }}
  PROMETHEUS_CONFIG_SYNC_INTERVAL: {{ .Values.config.interval | quote }}
  PROMETHEUS_CONFIG_SYNC_HTTP_TIMEOUT: {{ .Values.config.httpTimeout | quote }}
  PROMETHEUS_CONFIG_SYNC_VALIDATION_TIMEOUT: {{ .Values.config.validationTimeout | quote }}
  PROMETHEUS_CONFIG_SYNC_MAX_CONFIG_BYTES: {{ .Values.config.maxConfigBytes | quote }}
  PROMETHEUS_CONFIG_SYNC_MAX_RULES_BYTES: {{ .Values.config.maxRulesBytes | quote }}
  PROMETHEUS_CONFIG_SYNC_WEB_METRICS_PATH: {{ .Values.config.metricsPath | quote }}
  PROMETHEUS_CONFIG_SYNC_WEB_LISTEN_ADDRESS: {{ .Values.config.listenAddress | quote }}
