{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "prometheus-config-sync.fullname" . }}
  labels:
    {{- include "prometheus-config-sync.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "prometheus-config-sync.selectorLabels" . | nindent 6 }}
{{- end }}
