{{- if .Values.sourceAuth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-config-sync.fullname" . }}
  labels:
    {{- include "prometheus-config-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.sourceAuth.existingSecretKey | quote }}: {{ .Values.sourceAuth.token | quote }}
{{- end }}
